// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Name         string `json:"name"`
	Desc         string `json:"desc"`
	Stock        int64  `json:"stock"`
	Amount       int64  `json:"amount"`
	Screenwriter string `json:"screenwriter"`
	Director     string `json:"director"`
	Length       int64  `json:"length"`
	IsSelectSeat int64  `json:"isSelectSeat"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type UpdateRequest struct {
	Id           int64  `json:"id"`
	Name         string `json:"name,optional"`
	Desc         string `json:"desc,optional"`
	Stock        int64  `json:"stock,optional"`
	Amount       int64  `json:"amount,optional"`
	Screenwriter string `json:"screenwriter,optional"`
	Director     string `json:"director,optional"`
	Length       int64  `json:"length,optional"`
	IsSelectSeat int64  `json:"isSelectSeat,optional"`
}

type UpdateResponse struct {
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Name         string `json:"name"`
	Desc         string `json:"desc"`
	Stock        int64  `json:"stock"`
	Amount       int64  `json:"amount"`
	Screenwriter string `json:"screenwriter"`
	Director     string `json:"director"`
	Length       int64  `json:"length"`
	IsSelectSeat int64  `json:"isSelectSeat"`
}

type SaleListResponse struct {
	List []*Film `json:"list"`
}

type Film struct {
	Name         string `json:"name"`
	Desc         string `json:"desc"`
	Stock        int64  `json:"stock"`
	Amount       int64  `json:"amount"`
	Screenwriter string `json:"screenwriter"`
	Director     string `json:"director"`
	Length       int64  `json:"length"`
	IsSelectSeat int64  `json:"isSelectSeat"`
}
