// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Fid         int64  `json:"fid"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	IsAnonymous int64  `json:"isAnonymous"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type UpdateRequest struct {
	Id          int64  `json:"id"`
	Fid         int64  `json:"fid,optional"`
	Title       string `json:"title,optional"`
	Content     string `json:"content,optional"`
	IsAnonymous int64  `json:"isAnonymous,optional"`
}

type UpdateResponse struct {
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Fid         int64  `json:"fid"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	IsAnonymous int64  `json:"isAnonymous"`
}

type ListRequest struct {
}

type ListResponse struct {
	List []*UserComment `json:"list"`
}

type UserComment struct {
	Id          int64  `json:"id"`
	Fid         int64  `json:"fid"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	IsAnonymous int64  `json:"isAnonymous"`
}
