// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Fid    int64 `json:"fid"`
	Amount int64 `json:"amount"`
	Status int64 `json:"status"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type UpdateRequest struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid,optional"`
	Fid    int64 `json:"fid,optional"`
	Amount int64 `json:"amount,optional"`
	Status int64 `json:"status,optional"`
}

type UpdateResponse struct {
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Uid    int64 `json:"uid"`
	Fid    int64 `json:"fid"`
	Amount int64 `json:"amount"`
	Status int64 `json:"status"`
}

type ListResponse struct {
	List []*UserOrder `json:"list"`
}

type PaidListResponse struct {
	List []*UserOrder `json:"list"`
}

type UserOrder struct {
	Id     int64 `json:"id"`
	Uid    int64 `json:"uid"`
	Fid    int64 `json:"fid"`
	Amount int64 `json:"amount"`
	Status int64 `json:"status"`
}
